# .zshrc
# --- Shell config + command execution

# Autocompletion
autoload -U compinit; compinit
_comp_options+=(globdots) # With hidden files

# Prompt
fpath=($DOTFILES/zsh $fpath)
autoload -Uz prompt; prompt

# Options
setopt AUTO_PUSHD           # Push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # Do not store duplicates in the stack.
setopt PUSHD_SILENT         # Do not print the directory stack after pushd or popd.

# Plugins
fpath=($ZPLUGINSDIR/zsh-completions/src $fpath)     # zsh-completions
source $ZPLUGINSDIR/bd.zsh                          # zsh-bd
eval "$(mcfly init zsh)"                            # mcfly

eval $(~/.linuxbrew/bin/brew shellenv)              # Homebrew

# Aliases + functions
source $DOTFILES/aliases
source $DOTFILES/functions

# Highlighting
source $ZPLUGINSDIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh